### ISSUE TITLE
Nothingness accumulated snow

### ISSUE THREAD

**Issue by ghost** [kreezxil/god-block#24]
My God Block game started me in a snowy biome and snow's been accumulating way up near the height limit. It's a very weird effect. Especially the curve of a river off to one side.

**Comment by kreezxil** [comment]
oops just realized that I realized wrong

**Comment by kreezxil** [comment]
I could probably add stupid code to the block itself that checks to see if it is at build height and if it is, checks block above it which should null, but if it isn't that block is deleted. However, that is a very dirt kludge and will likely reek lots of havoc and incur severe tick lag in snowy biomes.

Alternatively, since it is really a pack issue and not block issue, ... there should be a way to disable weather in the main dimension. here's hoping.

**Comment by kreezxil** [comment]
hopefully fixed by changing world and island biome types to ocean. we shall see. i'll test this very shortly.

**Comment by kreezxil** [comment]
that seems to have been the solution all along. I'll mark it as fixed and if anyone has this issue again, simply start a new issue.

thanks.

**Comment by kreezxil** [comment]
did you start with a brand new world? and a fresh install of the pack, the
configs are now set for ocean biome for everything, there should be no more
rivers. The only way you can experience what you described is you have a
partial not fresh install of the pack.
