### ISSUE TITLE
No way to reach Nether or End in 1.5.6

### ISSUE THREAD

**Issue by GrokDuckFarmer** [kreezxil/god-block#7]
Currently there is no way to reach the Nether or End dimensions with pack version 1.5.6

**Repro steps:**
1. Start a new God Block world.
2. Ignite a vanilla Nether portal with flint and steel and walk into it.

**Expected:**
I should get transported to the Nether.

**Actual:**
I go nowhere.  And since the void world is devoid of Strongholds, there's no way to reach the End, either.  Hearth Well has a way of making blaze powder, so an End Cake would work if added.  The Nether could be reached with a Nether Cake or just making sure the portal works.

**Versions:**
 - Minecraft: 1.12.2
 - Forge: forge-14.23.5.2836
 - Mod Pack: 1.5.6

**Comment by kreezxil** [comment]
Hearthwell now disables the nether and possibly the end.

Generating either should be irrelevant with mystcraft existing, however I can see where it makes an issue with astral sorcery.

Yes I can add the cakes in the next update.

**Comment by kreezxil** [comment]
This is by design according to the hwell author, it's on the wiki you keep reading. You get nether crystals by throwing crystals thru a nether portal, but the crystals and you won't travel to the nether. And with mystcraft in the pack, I don't think there is a need for the nether other than that too. That may effecitively kill the OP parts of tinkers and otherwise gate the nether quartz based recipes. Again that should not matter because of a mystcraft dimension.

I'll make 1.6.7 today and release it to you on the down low, ie before it goes to curseforge to see if going to the nether or the end is really honestly needed.

**Comment by kreezxil** [comment]
ok, ok, it's an issue, because of astral sorcery.

let's think for a moment, do we need astral sorcery?

**Comment by kreezxil** [comment]
I have a solution, I'm not going to add cakes. But I will add one of the aether mods. So that we can craft a portal that takes us to the aether and there the astral skyrender will be allowed.
